FROM __BASEIMAGE_ARCH__/alpine
MAINTAINER Jonathan Weisberg <jo.weisberg@gmail.com>

__CROSS_COPY qemu-__QEMU_ARCH__-static /usr/bin
RUN apk --no-cache --update add \
    bash \
    openssl \
    jq

WORKDIR /root

COPY dyndns.sh /root/dyndns.sh
RUN chmod +x /root/dyndns.sh

CMD ["/bin/bash", "/root/dyndns.sh"]