FROM __BASEIMAGE_ARCH__/alpine
MAINTAINER Jonathan Weisberg <jo.weisberg@gmail.com>

__CROSS_COPY qemu-__QEMU_ARCH__-static /usr/bin
RUN apk --no-cache --update add bash tzdata curl ca-certificates
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /root

COPY dyndns.sh /root/dyndns.sh
COPY healthcheck /usr/bin/healthcheck
RUN chmod +x /usr/bin/healthcheck

CMD ["/bin/bash", "/root/dyndns.sh"]